version: "2.1"

# This docker-compose file has to be used for local development.
# A local running database will be created before the service will be started.
#
# @see https://docs.docker.com/compose/overview/
#
# docker-compose up -d
#

services:
  rem213-postgres:
    image: postgres:12.4
    container_name: rem213-postgres
    mem_limit: 50m
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "rem213"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - local-bridge

  rem213-backend:
    image: rem213-backend:junit
    build: .
    container_name: rem213-backend
    mem_limit: 512m
    depends_on:
      - rem213-postgres
    ports:
      - "8080:8080"
    networks:
      - local-bridge
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  local-bridge: # default network
    driver: bridge
